version: '3.7'

services:
  app:
    build:
      context: ./sn
      dockerfile: Dockerfile
    volumes:
      - ./sn/:/sn/
      - /var/run/docker.sock:/var/run/docker.sock
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8080
    env_file:
      - ./sn/.env
    ports:
      - 8080:8080

  db:
    image: library/postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./sn/.env
    ports:
      - 5432:5432
volumes:
  postgres_data: